#!/usr/bin/env node
import { createHash } from "node:crypto";
import {
  copyFile,
  mkdir,
  mkdtemp,
  readFile,
  rename,
  rm,
  writeFile,
} from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { parseArgs } from "node:util";
import { runtimeEntries, sourceFiles, run } from "./bootstrap.mjs";

export const packageEntries = [
  ...runtimeEntries,
  "README.md",
  "SKILL.md",
  "agents",
  "references",
  "skills",
  "distribution",
  "plugin.json",
  ".codex-plugin",
  ".claude-plugin",
];

export async function packagePlugin(source, output) {
  const pkg = JSON.parse(
    await readFile(path.join(source, "package.json"), "utf8"),
  );
  if (!/^\d+\.\d+\.\d+(?:-[a-zA-Z0-9.-]+)?$/.test(pkg.version))
    throw new Error("Package version must be semver.");
  for (const filename of [
    "plugin.json",
    ".codex-plugin/plugin.json",
    ".claude-plugin/plugin.json",
  ]) {
    const manifest = JSON.parse(
      await readFile(path.join(source, filename), "utf8"),
    );
    if (manifest.name !== "planorama" || manifest.version !== pkg.version)
      throw new Error(`${filename} must match package.json name and version.`);
  }
  await mkdir(output, { recursive: true });
  const staging = await mkdtemp(path.join(output, ".package-"));
  const name = `planorama-${pkg.version}`;
  const directory = path.join(staging, name);
  const plugin = path.join(directory, "plugins", "planorama");
  const files = await sourceFiles(source, packageEntries);
  try {
    for (const file of files) {
      const target = path.join(plugin, file);
      await mkdir(path.dirname(target), { recursive: true });
      await copyFile(path.join(source, file), target);
    }
    for (const [folder, template] of [
      [".agents/plugins", "codex-marketplace.json"],
      [".claude-plugin", "claude-marketplace.json"],
    ]) {
      await mkdir(path.join(directory, folder), { recursive: true });
      await copyFile(
        path.join(source, "distribution", template),
        path.join(directory, folder, "marketplace.json"),
      );
    }
    await copyFile(
      path.join(source, "distribution/INSTALL.md"),
      path.join(directory, "INSTALL.md"),
    );
    const inventory = [];
    for (const file of files)
      inventory.push({
        file: `plugins/planorama/${file.split(path.sep).join("/")}`,
        sha256: createHash("sha256")
          .update(await readFile(path.join(plugin, file)))
          .digest("hex"),
      });
    await writeFile(
      path.join(directory, "PACKAGE.json"),
      JSON.stringify(
        { name: "planorama", version: pkg.version, files: inventory },
        null,
        2,
      ) + "\n",
    );
    const archiveName = `${name}.tar.gz`;
    await run(
      "tar",
      ["-czf", path.join(staging, archiveName), "-C", staging, name],
      { env: { ...process.env, COPYFILE_DISABLE: "1" } },
    );
    const archive = await readFile(path.join(staging, archiveName));
    const checksum = createHash("sha256").update(archive).digest("hex");
    // Only replace a previous package generated by this command.
    const destination = path.join(output, name);
    try {
      const previous = JSON.parse(
        await readFile(path.join(destination, "PACKAGE.json"), "utf8"),
      );
      if (previous.name !== "planorama" || previous.version !== pkg.version)
        throw new Error("Refusing to replace an unrelated directory.");
      await rm(destination, { recursive: true });
    } catch (error) {
      if (error.code !== "ENOENT") throw error;
    }
    await rename(directory, destination);
    await rename(
      path.join(staging, archiveName),
      path.join(output, archiveName),
    );
    await writeFile(
      path.join(output, `${archiveName}.sha256`),
      `${checksum}  ${archiveName}\n`,
    );
    return {
      directory: destination,
      archive: path.join(output, archiveName),
      sha256: checksum,
      files: files.length,
    };
  } finally {
    await rm(staging, { recursive: true, force: true });
  }
}

if (
  process.argv[1] &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  try {
    const { values } = parseArgs({
      options: { out: { type: "string", default: "dist" } },
    });
    const source = path.resolve(
      path.dirname(fileURLToPath(import.meta.url)),
      "..",
    );
    console.log(
      JSON.stringify(
        await packagePlugin(source, path.resolve(values.out)),
        null,
        2,
      ),
    );
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
